[package]
name = "keygen"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "keygen"
path = "src/bin/keygen.rs"

[dependencies]
schnorrkel = { version = "0.10.2", features = ["getrandom"] }
hex = "0.4"
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
