[package]
name = "runtime"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "blockchain"
path = "src/bin/blockchain.rs"

[dependencies]
thiserror = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
wgpu = "25"
pollster = "0.3"
bytemuck = { version = "1.14", features = ["derive"] }
rand = "0.8"
sha2 = "0.10"
smartcore = { version = "0.4", default-features = false, features = ["datasets"] }
rayon = "1"
chrono = { version = "0.4.41", features = ["serde"] }
clap = { version = "4.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
keygen_lib = { package = "keygen", path = "../keygen" }
