[package]
name = "runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "1"
serde = { version = "1", features = ["derive"] }
wgpu = "25"
pollster = "0.3"
bytemuck = { version = "1.14", features = ["derive"] }
rand = "0.8"
sha2 = "0.10"
smartcore = { version = "0.4", default-features = false, features = ["datasets"] }

[dev-dependencies]
keygen_lib = { package = "keygen", path = "../keygen" }
