name: Continuous Integration

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        crate: [jobmanager, runtime, devnet, keygen, dashboard, p2p]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Rust format check
        run: cargo fmt --package ${{ matrix.crate }} -- --check
      
      - name: Clippy
        run: cargo clippy --package ${{ matrix.crate }} -- -D warnings
      
      - name: Run tests
        run: cargo test --package ${{ matrix.crate }} --verbose

  integration-test:
    runs-on: ubuntu-latest
    needs: lint-test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Build all crates
        run: cargo build --workspace
      
      - name: Run all tests
        run: cargo test --workspace --verbose
      
      - name: Test CLI binaries
        run: |
          # Build and test CLI tools
          cargo build --release
          ./target/release/bcai --help
          ./target/release/blockchain --help

  build:
    runs-on: ubuntu-latest
    needs: integration-test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Production build
        run: cargo build --release --workspace
      
      - name: Verify build artifacts
        run: |
          # Verify all binaries were built successfully
          ls -la target/release/
          ./target/release/bcai --version || echo "bcai version not available"
          ./target/release/blockchain --version || echo "blockchain version not available"
      
      - name: Build documentation
        run: cargo doc --workspace --no-deps
      
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bcai-binaries
          path: |
            target/release/bcai
            target/release/blockchain
          retention-days: 30
